server:
  port: 8082
  tomcat:
    max-connections: 10000
    max-threads: 1000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: 10.242.96.105
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.xa.DruidXADataSource

  application:
    name: shiro1

mybatis:
  mapper-locations: classpath:mapper/*.xml



